name = "backend"
compatibility_date = "2023-12-01"
# our development file will pick this url
# and .env file's url will be used by prisma cli to do migration or generating clients
 [vars]
 DATABASE_URL= "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNzFkNGRlNjgtNDc3Ni00MDQwLTgyMzQtYjFkOGExZDcyYzc2IiwidGVuYW50X2lkIjoiNTVlNDk5YzQ5YzJlN2FiMGM0YmFkZGU1MTcxNDhhYTFjNGMyODg1MTYxOTQ0MmQ2ODgyZWUyNjM2MDA2OGZhYiIsImludGVybmFsX3NlY3JldCI6ImFjMTgzNzY5LWU1NTMtNGJiNy05YzI3LTZmZDVjZWVmZTlkMyJ9.mX9Wxbcn3aDTtfTy4a-BZIRZDOgt8kva5hBMGKaL1UQ"
 JWT_SECRET="fuckoff"
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"